# In the following requests the variable baseUrl is used.
# Its value is set here.
@baseUrl = http://localhost:43265

### ------------------------------------------------------------------------
# Get Service Metadata Document
GET {{baseUrl}}/service/QmService/$metadata

### ------------------------------------------------------------------------
# Get Employee-Service
GET {{baseUrl}}/service/QmService/Employee

### ------------------------------------------------------------------------
# Retrieve the ID of the employee with the name 'Quin'
# Use this ID to call the submitOrder action
# @name getEmployeeID
GET {{baseUrl}}/service/QmService/Employee?$filter=firstname eq 'Quin'

###

@employeeID = {{getEmployeeID.response.body.$.value[0].employee_ID}}

### ------------------------------------------------------------------------
# Retrieve the ID of first Workplace 
# Use this ID to call the submitOrder action
# @name getWorkplace
GET {{baseUrl}}/service/QmService/Workplace?$filter=status eq 'OK'&$top=1

###



@workplaceID = {{getWorkplace.response.body.$.value[0].worplace_ID}}

POST {{baseUrl}}/service/QmService/createBooking
Content-Type: application/json

{
  "employee_ID": "{{employeeID}}",
  "workplace_ID": "{{workplaceID}}",
  "date": 2
}