/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const createbooking_Logic = require('./code/createbooking-logic');
const deletebooking_Logic = require('./code/deletebooking-logic');

class QmService extends LCAPApplicationService {
    async init() {

        this.on('createBooking', async (request, next) => {
            return createbooking_Logic(this.entities, request);
        });

        this.on('deleteBooking', async (request, next) => {
            return deletebooking_Logic(this.entities, request);
        });

        return super.init();
    }
}


module.exports = {
    QmService
};