/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const createbooking_Logic = require('./code/createbooking-logic');

class QmService extends LCAPApplicationService {
    async init() {

        this.on('createBooking', async (request, next) => {
            return createbooking_Logic(request);
        });

        return super.init();
    }
}


module.exports = {
    QmService
};